version: "3.8"
services:
    interbtc:
        image: "interlayhq/interbtc:interbtc-standalone-0.8.5"
        command:
            - interbtc-standalone
            - --dev
            - --unsafe-rpc-external
            - --unsafe-ws-external
            - --rpc-methods
            - Unsafe
        ports:
            - "9933:9933"
            - "9944:9944"
    oracle:
        image: "interlayhq/interbtc-clients:oracle-0-8-2"
        command:
            - oracle
            - --keyring
            - bob
            - --polka-btc-url
            - "ws://polkabtc:9944"
        environment:
            RUST_LOG: info
        restart: unless-stopped
    faucet:
        image: "interlayhq/interbtc-clients:faucet-0-8-2"
        command:
            - faucet
            - --keyring
            - ferdie
            - --btc-parachain-url
            - "ws://interbtc:9944"
            - --user-allowance
            - "1"
            - --vault-allowance
            - "500"
            - --http-addr
            - "[::0]:3035"
        environment:
            RUST_LOG: info
        ports:
            - "3035:3035"
        restart: unless-stopped
    vault:
        image: "interlayhq/interbtc-clients:vault-0-8-2"
        command:
            - vault
            - --keyring
            - charlie
            - --network
            - testnet
            - --auto-register-with-collateral
            - "100000000000000"
            - --btc-parachain-url
            - "ws://polkabtc:9944"
        environment:
            <<: *client-env
        restart: unless-stopped
    postgres:
        image: "postgres:11"
        environment:
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "password"
        ports:
            - "5432:5432"
    interbtc_stats:
        image: "registry.gitlab.com/interlay/polkabtc-stats:0.5.7"
        restart: always
        depends_on:
            - postgres
        command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; yarn start'
        environment:
            MONITOR: "1"
            ENDPOINT_URL: "ws://polkabtc:9944"
            BTC_NETWORK: "http://electrs:3002"
            PGHOST: "postgres"
            PGPORT: "5432"
            PGDATABASE: "postgres"
            PGUSER: "user"
            PGPASSWORD: "password"
        ports:
            - "3007:3007"
